
import java.awt.Color;
import java.sql.*;
import static javafx.scene.control.ButtonBar.ButtonData.YES;
import javax.swing.*;
import javax.swing.text.Position;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SK
 */
public class SubmitFEES extends javax.swing.JFrame {
 final void FillList()
    {
    try{
        String url="jdbc:h2:~/test";
        
     Connection con = DriverManager.getConnection(url,"sa",""); 
     Statement stmt=con.createStatement();
     String Query="SELECT * FROM STUDENT ORDER BY ADNO";
     ResultSet rs=stmt.executeQuery(Query);
     DefaultListModel DLM= new DefaultListModel();
     while(rs.next())
     {
     DLM.addElement(rs.getString(1));
     }
     l2.setModel(DLM);
    }
    catch(SQLException ex) 
       {
       JOptionPane.showMessageDialog(null, ex.toString());
       }
    }

    /**
     * Creates new form SubmitFEES
     */
    public SubmitFEES() {
        initComponents();FillList();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(255,255,153));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        l2 = new javax.swing.JList();
        jLabel24 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        mob = new javax.swing.JTextField();
        july = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        nov = new javax.swing.JTextField();
        adno = new javax.swing.JTextField();
        jan = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        dob = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        sec = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        add = new javax.swing.JTextField();
        feb = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        april = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        may = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        march = new javax.swing.JTextField();
        clas = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dec = new javax.swing.JTextField();
        june = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        aug = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        sept = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        oct = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        co2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        tot = new javax.swing.JTextField();
        cb1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1320, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 135, 15));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home.jpg"))); // NOI18N
        jButton2.setText("     Return to HOME");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, -1, 48));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 2, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("**Designed By, Saurav Kumar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 660, 216, -1));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FEEs Submission Arena");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 797, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SESSION: 2016-2017");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("#Click on Admission No. to View Details.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel30.setFont(new java.awt.Font("Microsoft JhengHei", 0, 15)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("DataBase : STUDENT");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 241, -1));

        jLabel8.setBackground(new java.awt.Color(204, 255, 204));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("# Enter Admission No. :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        t2.setBackground(new java.awt.Color(204, 255, 204));
        t2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 341, -1));

        jButton5.setBackground(new java.awt.Color(0, 0, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("SEARCH   DataBase");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 339, 36));

        l2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Admission No.", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft JhengHei", 0, 14))); // NOI18N
        l2.setToolTipText("");
        l2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                l2ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(l2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 241, 280));

        jLabel24.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("(8-digits)");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 140, 115, -1));

        jLabel39.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel39.setText("November :");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, -1, -1));

        mob.setEditable(false);
        mob.setBackground(new java.awt.Color(255, 255, 204));
        mob.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        getContentPane().add(mob, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 507, -1));

        july.setEditable(false);
        july.setBackground(new java.awt.Color(255, 255, 204));
        july.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(july, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 50, -1));

        jLabel21.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("(50-characters)");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 170, 115, -1));

        jLabel36.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel36.setText("August :");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, -1, -1));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Father's Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 131, -1));

        jLabel22.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("(50-characters)");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 200, 115, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Date Of Birth (DOB)");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        jLabel23.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("YYYY-MM-DD");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 230, 115, -1));

        jLabel26.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel26.setText("+91");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, -1, -1));

        jLabel27.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel27.setText(" : ");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, -1));

        jLabel28.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel28.setText(" : ");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));

        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Section");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 138, -1));

        jLabel29.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel29.setText(" : ");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, -1, -1));

        nov.setEditable(false);
        nov.setBackground(new java.awt.Color(255, 255, 204));
        nov.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(nov, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 480, 50, -1));

        adno.setEditable(false);
        adno.setBackground(new java.awt.Color(255, 255, 204));
        adno.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        getContentPane().add(adno, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 537, -1));

        jan.setEditable(false);
        jan.setBackground(new java.awt.Color(255, 255, 204));
        jan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(jan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 480, 50, -1));

        jLabel25.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("(100-characters)");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 320, 115, -1));

        jLabel40.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel40.setText("December :");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 450, -1, -1));

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Address");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 138, -1));

        fname.setEditable(false);
        fname.setBackground(new java.awt.Color(255, 255, 204));
        fname.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 537, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 102, 102));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Fees Not Paid=\"NO\"");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 510, 137, 37));

        dob.setEditable(false);
        dob.setBackground(new java.awt.Color(255, 255, 204));
        dob.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 537, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 102, 102));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Fees Paid=\"YES\"");
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 510, 126, 37));

        sec.setEditable(false);
        sec.setBackground(new java.awt.Color(255, 255, 204));
        sec.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        getContentPane().add(sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 537, -1));

        jLabel44.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel44.setText("February :");
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 450, -1, -1));

        add.setEditable(false);
        add.setBackground(new java.awt.Color(255, 255, 204));
        add.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 537, -1));

        feb.setEditable(false);
        feb.setBackground(new java.awt.Color(255, 255, 204));
        feb.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(feb, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 450, 50, -1));

        jLabel32.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel32.setText("April :");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 0, 204));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("# Fee Status #");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, -1, -1));

        april.setEditable(false);
        april.setBackground(new java.awt.Color(255, 255, 204));
        april.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(april, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 50, -1));

        jLabel33.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("May :");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, -1, -1));

        name.setEditable(false);
        name.setBackground(new java.awt.Color(255, 255, 204));
        name.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 537, -1));

        may.setEditable(false);
        may.setBackground(new java.awt.Color(255, 255, 204));
        may.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        may.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayActionPerformed(evt);
            }
        });
        getContentPane().add(may, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 50, -1));

        jLabel45.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel45.setText("March :");
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 480, -1, -1));

        march.setEditable(false);
        march.setBackground(new java.awt.Color(255, 255, 204));
        march.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(march, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 480, 50, -1));

        clas.setEditable(false);
        clas.setBackground(new java.awt.Color(255, 255, 204));
        clas.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        clas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasActionPerformed(evt);
            }
        });
        getContentPane().add(clas, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 538, -1));

        jLabel34.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("June :");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Admission No.*");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 131, -1));

        dec.setEditable(false);
        dec.setBackground(new java.awt.Color(255, 255, 204));
        dec.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(dec, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 450, 50, -1));

        june.setEditable(false);
        june.setBackground(new java.awt.Color(255, 255, 204));
        june.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(june, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, 50, -1));

        jLabel15.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Mobile No. ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 138, -1));

        jLabel16.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel16.setText(" : ");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 131, -1));

        jLabel41.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel41.setText("January :");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 480, -1, -1));

        jLabel17.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel17.setText(" : ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, -1, -1));

        jLabel35.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText("July :");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, -1, -1));

        jLabel18.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel18.setText(" : ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, -1, -1));

        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel19.setText(" : ");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, -1, -1));

        jLabel20.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel20.setText(" : ");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, -1));

        aug.setEditable(false);
        aug.setBackground(new java.awt.Color(255, 255, 204));
        aug.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(aug, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, 50, -1));

        jLabel37.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("September :");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, -1, -1));

        sept.setEditable(false);
        sept.setBackground(new java.awt.Color(255, 255, 204));
        sept.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(sept, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 480, 50, -1));

        jLabel38.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("October :");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 450, -1, -1));

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Class");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 138, -1));

        oct.setEditable(false);
        oct.setBackground(new java.awt.Color(255, 255, 204));
        oct.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(oct, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 450, 50, -1));

        jButton4.setBackground(new java.awt.Color(255, 0, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("*Pay FEEs Now !");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 550, 198, 46));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        jLabel7.setText("*Total Fee :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 560, -1, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("*Select MONTH :");
        getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, -1, -1));

        co2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        co2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "January", "February", "March", "April", "May", "June", "July", "August", "September", "November", "December" }));
        getContentPane().add(co2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, 150, -1));

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 153));
        jButton3.setText("Reset Fields");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 550, -1, 46));

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel46.setText("₹");
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 560, -1, 26));

        tot.setEditable(false);
        tot.setBackground(new java.awt.Color(204, 255, 204));
        tot.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tot.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(tot, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 560, 161, -1));

        cb1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cb1.setText("Include Bus Service.");
        getContentPane().add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 580, -1, -1));

        jButton1.setBackground(new java.awt.Color(102, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Show Total FEEs");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 610, 150, -1));

        jLabel47.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("(*April Fees includes Annual Fees also.)");
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 600, 217, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new FeeStructure().setVisible(false);
        new B().setVisible(true);  dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int result=l2.getNextMatch(t2.getText(), 0, Position.Bias.Forward);

        l2.setSelectedIndex(result);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void l2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_l2ValueChanged

        try{
            String url="jdbc:h2:~/test";

            Connection con = DriverManager.getConnection(url,"sa","");
            Statement stmt=con.createStatement();
            String Query="SELECT * FROM STUDENT where adno = '"+l2.getSelectedValue()+"'";
            ResultSet rs=stmt.executeQuery(Query);

            while(rs.next())
            {
                adno.setText(rs.getString(1));
                name.setText(rs.getString(2));
                fname.setText(rs.getString(3));
                dob.setText(rs.getString(4));
                clas.setText(rs.getString(5));
                sec.setText(rs.getString(6));
                add.setText(rs.getString(7));
                mob.setText(rs.getString(8));

                april.setText(rs.getString(9));
                may.setText(rs.getString(10));
                june.setText(rs.getString(11));
                july.setText(rs.getString(12));
                aug.setText(rs.getString(13));
                sept.setText(rs.getString(14));
                oct.setText(rs.getString(15));
                nov.setText(rs.getString(16));
                dec.setText(rs.getString(17));
                jan.setText(rs.getString(18));
                feb.setText(rs.getString(19));
                march.setText(rs.getString(20));

            }

        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_l2ValueChanged

    private void mayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mayActionPerformed

    private void clasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clasActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String c1=(String)clas.getText();
        String c2=(String)co2.getSelectedItem();

        if(l2.getSelectedValue()!=(null)&&  c1!=(null) && c2!=(null) && c2!=("Select"))
        {
        if(cb1.isSelected()==false)
        {
            if(c1.equals("Nursery")||c1.equals("Prep"))
            {
                switch(c2)
                {
                    case "April":tot.setText("7690"); break;
                    case "May":tot.setText("1260"); break;
                    case "June":tot.setText("1260"); break;
                    case "July":tot.setText("1260"); break;
                    case "August":tot.setText("1260"); break;
                    case "September":tot.setText("1260"); break;
                    case "October":tot.setText("1260"); break;
                    case "November":tot.setText("1260"); break;
                    case "December":tot.setText("1260"); break;
                    case "January":tot.setText("1260"); break;
                    case "February":tot.setText("1260"); break;
                    case "March":tot.setText("1260"); break;

                    default : JOptionPane.showMessageDialog(null,"Select *Month* First.");
                }
            }
            else
            if(c1.equals("1")||c1.equals("2")||c1.equals("3"))
            {
                switch(c2)
                {
                    case "April":tot.setText("8010"); break;
                    case "May":tot.setText("1310"); break;
                    case "June":tot.setText("1310"); break;
                    case "July":tot.setText("1310"); break;
                    case "August":tot.setText("1310"); break;
                    case "September":tot.setText("1310"); break;
                    case "October":tot.setText("1310"); break;
                    case "November":tot.setText("1310"); break;
                    case "December":tot.setText("1310"); break;
                    case "January":tot.setText("1310"); break;
                    case "February":tot.setText("1310"); break;
                    case "March":tot.setText("1310"); break;
                    default : JOptionPane.showMessageDialog(null,"Select *Month* First.");
                }
            }
            else
            if(c1.equals("4")||c1.equals("5"))
            {
                switch(c2)
                {
                    case "April":tot.setText("8110"); break;
                    case "May":tot.setText("1410"); break;
                    case "June":tot.setText("1410"); break;
                    case "July":tot.setText("1410"); break;
                    case "August":tot.setText("1410"); break;
                    case "September":tot.setText("1410"); break;
                    case "October":tot.setText("1410"); break;
                    case "November":tot.setText("1410"); break;
                    case "December":tot.setText("1410"); break;
                    case "January":tot.setText("1410"); break;
                    case "February":tot.setText("1410"); break;
                    case "March":tot.setText("1410"); break;
                    default : JOptionPane.showMessageDialog(null,"Select *Month* First.");
                }
            }
            else
            if(c1.equals("6")||c1.equals("7")||c1.equals("8"))
            {
                switch(c2)
                {
                    case "April":tot.setText("8240"); break;
                    case "May":tot.setText("1540"); break;
                    case "June":tot.setText("1540"); break;
                    case "July":tot.setText("1540"); break;
                    case "August":tot.setText("1540"); break;
                    case "September":tot.setText("1540"); break;
                    case "October":tot.setText("1540"); break;
                    case "November":tot.setText("1540"); break;
                    case "December":tot.setText("1540"); break;
                    case "January":tot.setText("1540"); break;
                    case "February":tot.setText("1540"); break;
                    case "March":tot.setText("1540"); break;
                    default : JOptionPane.showMessageDialog(null,"Select *Month* First.");
                }
            }
            else
            if(c1.equals("9")||c1.equals("10"))
            {
                switch(c2)
                {
                    case "April":tot.setText("8490"); break;
                    case "May":tot.setText("1790"); break;
                    case "June":tot.setText("1790"); break;
                    case "July":tot.setText("1790"); break;
                    case "August":tot.setText("1790"); break;
                    case "September":tot.setText("1790"); break;
                    case "October":tot.setText("1790"); break;
                    case "November":tot.setText("1790"); break;
                    case "December":tot.setText("1790"); break;
                    case "January":tot.setText("1790"); break;
                    case "February":tot.setText("1790"); break;
                    case "March":tot.setText("1790"); break;
                    default : JOptionPane.showMessageDialog(null,"Select *Month* First.");
                }
            }
            else
            if(c1.equals("11_COMMERCE")||c1.equals("11_Science"))
            {
                switch(c2)
                {
                    case "April":tot.setText("8580"); break;
                    case "May":tot.setText("1880"); break;
                    case "June":tot.setText("1880"); break;
                    case "July":tot.setText("1880"); break;
                    case "August":tot.setText("1880"); break;
                    case "September":tot.setText("1880"); break;
                    case "October":tot.setText("1880"); break;
                    case "November":tot.setText("1880"); break;
                    case "December":tot.setText("1880"); break;
                    case "January":tot.setText("1880"); break;
                    case "February":tot.setText("1880"); break;
                    case "March":tot.setText("1880"); break;
                    default : JOptionPane.showMessageDialog(null,"Select *Month* First.");
                }
            }
            else
            if(c1.equals("12_COMMERCE")||c1.equals("12_Science"))
            {
                switch(c2)
                {
                    case "April":tot.setText("8870"); break;
                    case "May":tot.setText("2170"); break;
                    case "June":tot.setText("2170"); break;
                    case "July":tot.setText("2170"); break;
                    case "August":tot.setText("2170"); break;
                    case "September":tot.setText("2170"); break;
                    case "October":tot.setText("2170"); break;
                    case "November":tot.setText("2170"); break;
                    case "December":tot.setText("2170"); break;
                    case "January":tot.setText("2170"); break;
                    case "February":tot.setText("2170"); break;
                    case "March":tot.setText("2170"); break;
                    default : JOptionPane.showMessageDialog(null,"Select *Month* First.");
                }
            }
            else
            JOptionPane.showMessageDialog(null,"*Class* not Retrieved. Select a Record from DataBase to retrieve Class.");
        }
        else
        if(cb1.isSelected()==true)
        {
            if(c1.equals("Nursery")||c1.equals("Prep"))
            {
                switch(c2)
                {

                    case "April":tot.setText("8260"); break;
                    case "May":tot.setText("1830"); break;
                    case "June":tot.setText("1830"); break;
                    case "July":tot.setText("1830"); break;
                    case "August":tot.setText("1830"); break;
                    case "September":tot.setText("1830"); break;
                    case "October":tot.setText("1830"); break;
                    case "November":tot.setText("1830"); break;
                    case "December":tot.setText("1830"); break;
                    case "January":tot.setText("1830"); break;
                    case "February":tot.setText("1830"); break;
                    case "March":tot.setText("1830"); break;

                    default : JOptionPane.showMessageDialog(null,"Select Month");
                }
            }
            else
            if(c1.equals("1")||c1.equals("2")||c1.equals("3"))
            {
                switch(c2)
                {
                    case "April":tot.setText("8580"); break;
                    case "May":tot.setText("1880"); break;
                    case "June":tot.setText("1880"); break;
                    case "July":tot.setText("1880"); break;
                    case "August":tot.setText("1880"); break;
                    case "September":tot.setText("1880"); break;
                    case "October":tot.setText("1880"); break;
                    case "November":tot.setText("1880"); break;
                    case "December":tot.setText("1880"); break;
                    case "January":tot.setText("1880"); break;
                    case "February":tot.setText("1880"); break;
                    case "March":tot.setText("1880"); break;
                    default : JOptionPane.showMessageDialog(null,"Select Month");
                }
            }
            else
            if(c1.equals("4")||c1.equals("5"))
            {
                switch(c2)
                {
                    case "April":tot.setText("8680"); break;
                    case "May":tot.setText("1980"); break;
                    case "June":tot.setText("1980"); break;
                    case "July":tot.setText("1980"); break;
                    case "August":tot.setText("1980"); break;
                    case "September":tot.setText("1980"); break;
                    case "October":tot.setText("1980"); break;
                    case "November":tot.setText("1980"); break;
                    case "December":tot.setText("1980"); break;
                    case "January":tot.setText("1980"); break;
                    case "February":tot.setText("1980"); break;
                    case "March":tot.setText("1980"); break;
                    default : JOptionPane.showMessageDialog(null,"Select Month");
                }
            }
            else
            if(c1.equals("6")||c1.equals("7")||c1.equals("8"))
            {
                switch(c2)
                {
                    case "April":tot.setText("8180"); break;
                    case "May":tot.setText("2110"); break;
                    case "June":tot.setText("2110"); break;
                    case "July":tot.setText("2110"); break;
                    case "August":tot.setText("2110"); break;
                    case "September":tot.setText("2110"); break;
                    case "October":tot.setText("2110"); break;
                    case "November":tot.setText("2110"); break;
                    case "December":tot.setText("2110"); break;
                    case "January":tot.setText("2110"); break;
                    case "February":tot.setText("2110"); break;
                    case "March":tot.setText("2110"); break;
                    default : JOptionPane.showMessageDialog(null,"Select Month");
                }
            }
            else
            if(c1.equals("9")||c1.equals("10"))
            {
                switch(c2)
                {
                    case "April":tot.setText("9060"); break;
                    case "May":tot.setText("2360"); break;
                    case "June":tot.setText("2360"); break;
                    case "July":tot.setText("2360"); break;
                    case "August":tot.setText("2360"); break;
                    case "September":tot.setText("2360"); break;
                    case "October":tot.setText("2360"); break;
                    case "November":tot.setText("2360"); break;
                    case "December":tot.setText("2360"); break;
                    case "January":tot.setText("2360"); break;
                    case "February":tot.setText("2360"); break;
                    case "March":tot.setText("2360"); break;
                    default : JOptionPane.showMessageDialog(null,"Select Month");
                }
            }
            else
            if(c1.equals("11_COMMERCE")||c1.equals("11_Science"))
            {
                switch(c2)
                {
                    case "April":tot.setText("9150"); break;
                    case "May":tot.setText("2450"); break;
                    case "June":tot.setText("2450"); break;
                    case "July":tot.setText("2450"); break;
                    case "August":tot.setText("2450"); break;
                    case "September":tot.setText("2450"); break;
                    case "October":tot.setText("2450"); break;
                    case "November":tot.setText("2450"); break;
                    case "December":tot.setText("2450"); break;
                    case "January":tot.setText("2450"); break;
                    case "February":tot.setText("2450"); break;
                    case "March":tot.setText("2450"); break;
                    default : JOptionPane.showMessageDialog(null,"Select Month");
                }
            }
            else
            if(c1.equals("12_COMMERCE")||c1.equals("12_Science"))
            {
                switch(c2)
                {
                    case "April":tot.setText("9440"); break;
                    case "May":tot.setText("2740"); break;
                    case "June":tot.setText("2740"); break;
                    case "July":tot.setText("2740"); break;
                    case "August":tot.setText("2740"); break;
                    case "September":tot.setText("2740"); break;
                    case "October":tot.setText("2740"); break;
                    case "November":tot.setText("2740"); break;
                    case "December":tot.setText("2740"); break;
                    case "January":tot.setText("2740"); break;
                    case "February":tot.setText("2740"); break;
                    case "March":tot.setText("2740"); break;
                    default : JOptionPane.showMessageDialog(null,"Select Month");
                }
            }
            else
            JOptionPane.showMessageDialog(null,"Select Class.");
        }
if(l2.getSelectedValue()!=(null)&&  c1!=(null) && c2!=(null) && c2!=("Select"))
{
        try{
            String url="jdbc:h2:~/test";

            Connection con = DriverManager.getConnection(url,"sa","");
            Statement stmt=con.createStatement();
            String x=(String)co2.getSelectedItem();
            switch(x){
                case "April": String Query="UPDATE STUDENT SET April='"+YES+"' WHERE adno='"+l2.getSelectedValue()+"' ";stmt.execute(Query);;break;
                case "May": String Query1="UPDATE STUDENT SET May='"+YES+"' WHERE adno='"+l2.getSelectedValue()+"' ";stmt.execute(Query1);;break;
                case "June": String Query2="UPDATE STUDENT SET June='"+YES+"' WHERE adno='"+l2.getSelectedValue()+"' ";stmt.execute(Query2);;break;
                case "July": String Query3="UPDATE STUDENT SET July='"+YES+"' WHERE adno='"+l2.getSelectedValue()+"' ";stmt.execute(Query3);;break;
                case "August": String Query4="UPDATE STUDENT SET Aug='"+YES+"' WHERE adno='"+l2.getSelectedValue()+"' ";stmt.execute(Query4);;break;

                case "September": String Query5="UPDATE STUDENT SET Sept='"+YES+"' WHERE adno='"+l2.getSelectedValue()+"' ";stmt.execute(Query5);;break;

                case "October": String Query6="UPDATE STUDENT SET oct='"+YES+"' WHERE adno='"+l2.getSelectedValue()+"' ";stmt.execute(Query6);;break;

                case "November": String Query7="UPDATE STUDENT SET nov='"+YES+"' WHERE adno='"+l2.getSelectedValue()+"' ";stmt.execute(Query7);;break;

                case "December": String Query8="UPDATE STUDENT SET dec='"+YES+"' WHERE adno='"+l2.getSelectedValue()+"' ";stmt.execute(Query8);;break;

                case "January": String Query9="UPDATE STUDENT SET jan='"+YES+"' WHERE adno='"+l2.getSelectedValue()+"' ";stmt.execute(Query9);;break;

                case "February": String Query10="UPDATE STUDENT SET feb='"+YES+"' WHERE adno='"+l2.getSelectedValue()+"' ";stmt.execute(Query10);;break;

                case "March": String Query11="UPDATE STUDENT SET march='"+YES+"' WHERE adno='"+l2.getSelectedValue()+"' ";stmt.execute(Query11);;break;

                default:
            }
            
JOptionPane.showMessageDialog(null,"FEEs Paid & DataBase Updated Successfully.");
        }

        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        
        FillList();

        t2.setText("");
        adno.setText(null);
        name.setText(null);
        fname.setText(null);
        dob.setText(null);
        clas.setText(null);
        sec.setText(null);
        add.setText(null);
        mob.setText(null);
co2.setSelectedItem("Select"); tot.setText("");cb1.setSelected(false);
        april.setText(null);
        may.setText(null);
        june.setText(null);
        july.setText(null);
        aug.setText(null);
        sept.setText(null);
        oct.setText(null);
        nov.setText(null);
        dec.setText(null);
        jan.setText(null);
        feb.setText(null);
        march.setText(null);
}else
{

}}else
            if(c2==("Select") && l2.getSelectedValue()!=(null)&&  c1!=(null) && c2!=(null))
            {JOptionPane.showMessageDialog(null,"Select MONTH.");}
        else
        {JOptionPane.showMessageDialog(null,"No Record(s) Selected.");}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cb1.setSelected(false);
        co2.setSelectedItem("Select");
        tot.setText(null);
        t2.setText("");
        adno.setText(null);
        name.setText(null);
        fname.setText(null);
        dob.setText(null);
        clas.setText(null);
        sec.setText(null);
        add.setText(null);
        mob.setText(null);

        april.setText(null);
        may.setText(null);
        june.setText(null);
        july.setText(null);
        aug.setText(null);
        sept.setText(null);
        oct.setText(null);
        nov.setText(null);
        dec.setText(null);
        jan.setText(null);
        feb.setText(null);
        march.setText(null);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String c1=(String)clas.getText();
        String c2=(String)co2.getSelectedItem();

        if(cb1.isSelected()==false)
        {
            if(c1.equals("Nursery")||c1.equals("Prep"))
            {
                switch(c2)
                {
                    case "April":tot.setText("7690"); break;
                    case "May":tot.setText("1260"); break;
                    case "June":tot.setText("1260"); break;
                    case "July":tot.setText("1260"); break;
                    case "August":tot.setText("1260"); break;
                    case "September":tot.setText("1260"); break;
                    case "October":tot.setText("1260"); break;
                    case "November":tot.setText("1260"); break;
                    case "December":tot.setText("1260"); break;
                    case "January":tot.setText("1260"); break;
                    case "February":tot.setText("1260"); break;
                    case "March":tot.setText("1260"); break;

                    default : JOptionPane.showMessageDialog(null,"Select *Month* First.");
                }
            }
            else
            if(c1.equals("1")||c1.equals("2")||c1.equals("3"))
            {
                switch(c2)
                {
                    case "April":tot.setText("8010"); break;
                    case "May":tot.setText("1310"); break;
                    case "June":tot.setText("1310"); break;
                    case "July":tot.setText("1310"); break;
                    case "August":tot.setText("1310"); break;
                    case "September":tot.setText("1310"); break;
                    case "October":tot.setText("1310"); break;
                    case "November":tot.setText("1310"); break;
                    case "December":tot.setText("1310"); break;
                    case "January":tot.setText("1310"); break;
                    case "February":tot.setText("1310"); break;
                    case "March":tot.setText("1310"); break;
                    default : JOptionPane.showMessageDialog(null,"Select *Month* First.");
                }
            }
            else
            if(c1.equals("4")||c1.equals("5"))
            {
                switch(c2)
                {
                    case "April":tot.setText("8110"); break;
                    case "May":tot.setText("1410"); break;
                    case "June":tot.setText("1410"); break;
                    case "July":tot.setText("1410"); break;
                    case "August":tot.setText("1410"); break;
                    case "September":tot.setText("1410"); break;
                    case "October":tot.setText("1410"); break;
                    case "November":tot.setText("1410"); break;
                    case "December":tot.setText("1410"); break;
                    case "January":tot.setText("1410"); break;
                    case "February":tot.setText("1410"); break;
                    case "March":tot.setText("1410"); break;
                    default : JOptionPane.showMessageDialog(null,"Select *Month* First.");
                }
            }
            else
            if(c1.equals("6")||c1.equals("7")||c1.equals("8"))
            {
                switch(c2)
                {
                    case "April":tot.setText("8240"); break;
                    case "May":tot.setText("1540"); break;
                    case "June":tot.setText("1540"); break;
                    case "July":tot.setText("1540"); break;
                    case "August":tot.setText("1540"); break;
                    case "September":tot.setText("1540"); break;
                    case "October":tot.setText("1540"); break;
                    case "November":tot.setText("1540"); break;
                    case "December":tot.setText("1540"); break;
                    case "January":tot.setText("1540"); break;
                    case "February":tot.setText("1540"); break;
                    case "March":tot.setText("1540"); break;
                    default : JOptionPane.showMessageDialog(null,"Select *Month* First.");
                }
            }
            else
            if(c1.equals("9")||c1.equals("10"))
            {
                switch(c2)
                {
                    case "April":tot.setText("8490"); break;
                    case "May":tot.setText("1790"); break;
                    case "June":tot.setText("1790"); break;
                    case "July":tot.setText("1790"); break;
                    case "August":tot.setText("1790"); break;
                    case "September":tot.setText("1790"); break;
                    case "October":tot.setText("1790"); break;
                    case "November":tot.setText("1790"); break;
                    case "December":tot.setText("1790"); break;
                    case "January":tot.setText("1790"); break;
                    case "February":tot.setText("1790"); break;
                    case "March":tot.setText("1790"); break;
                    default : JOptionPane.showMessageDialog(null,"Select *Month* First.");
                }
            }
            else
            if(c1.equals("11_COMMERCE")||c1.equals("11_Science"))
            {
                switch(c2)
                {
                    case "April":tot.setText("8580"); break;
                    case "May":tot.setText("1880"); break;
                    case "June":tot.setText("1880"); break;
                    case "July":tot.setText("1880"); break;
                    case "August":tot.setText("1880"); break;
                    case "September":tot.setText("1880"); break;
                    case "October":tot.setText("1880"); break;
                    case "November":tot.setText("1880"); break;
                    case "December":tot.setText("1880"); break;
                    case "January":tot.setText("1880"); break;
                    case "February":tot.setText("1880"); break;
                    case "March":tot.setText("1880"); break;
                    default : JOptionPane.showMessageDialog(null,"Select *Month* First.");
                }
            }
            else
            if(c1.equals("12_COMMERCE")||c1.equals("12_Science"))
            {
                switch(c2)
                {
                    case "April":tot.setText("8870"); break;
                    case "May":tot.setText("2170"); break;
                    case "June":tot.setText("2170"); break;
                    case "July":tot.setText("2170"); break;
                    case "August":tot.setText("2170"); break;
                    case "September":tot.setText("2170"); break;
                    case "October":tot.setText("2170"); break;
                    case "November":tot.setText("2170"); break;
                    case "December":tot.setText("2170"); break;
                    case "January":tot.setText("2170"); break;
                    case "February":tot.setText("2170"); break;
                    case "March":tot.setText("2170"); break;
                    default : JOptionPane.showMessageDialog(null,"Select *Month* First.");
                }
            }
            else
            JOptionPane.showMessageDialog(null,"*Class* not Retrieved. Select a Record from DataBase to retrieve Class.");
        }
        else
        if(cb1.isSelected()==true)
        {
            if(c1.equals("Nursery")||c1.equals("Prep"))
            {
                switch(c2)
                {

                    case "April":tot.setText("8260"); break;
                    case "May":tot.setText("1830"); break;
                    case "June":tot.setText("1830"); break;
                    case "July":tot.setText("1830"); break;
                    case "August":tot.setText("1830"); break;
                    case "September":tot.setText("1830"); break;
                    case "October":tot.setText("1830"); break;
                    case "November":tot.setText("1830"); break;
                    case "December":tot.setText("1830"); break;
                    case "January":tot.setText("1830"); break;
                    case "February":tot.setText("1830"); break;
                    case "March":tot.setText("1830"); break;

                    default : JOptionPane.showMessageDialog(null,"Select Month");
                }
            }
            else
            if(c1.equals("1")||c1.equals("2")||c1.equals("3"))
            {
                switch(c2)
                {
                    case "April":tot.setText("8580"); break;
                    case "May":tot.setText("1880"); break;
                    case "June":tot.setText("1880"); break;
                    case "July":tot.setText("1880"); break;
                    case "August":tot.setText("1880"); break;
                    case "September":tot.setText("1880"); break;
                    case "October":tot.setText("1880"); break;
                    case "November":tot.setText("1880"); break;
                    case "December":tot.setText("1880"); break;
                    case "January":tot.setText("1880"); break;
                    case "February":tot.setText("1880"); break;
                    case "March":tot.setText("1880"); break;
                    default : JOptionPane.showMessageDialog(null,"Select Month");
                }
            }
            else
            if(c1.equals("4")||c1.equals("5"))
            {
                switch(c2)
                {
                    case "April":tot.setText("8680"); break;
                    case "May":tot.setText("1980"); break;
                    case "June":tot.setText("1980"); break;
                    case "July":tot.setText("1980"); break;
                    case "August":tot.setText("1980"); break;
                    case "September":tot.setText("1980"); break;
                    case "October":tot.setText("1980"); break;
                    case "November":tot.setText("1980"); break;
                    case "December":tot.setText("1980"); break;
                    case "January":tot.setText("1980"); break;
                    case "February":tot.setText("1980"); break;
                    case "March":tot.setText("1980"); break;
                    default : JOptionPane.showMessageDialog(null,"Select Month");
                }
            }
            else
            if(c1.equals("6")||c1.equals("7")||c1.equals("8"))
            {
                switch(c2)
                {
                    case "April":tot.setText("8180"); break;
                    case "May":tot.setText("2110"); break;
                    case "June":tot.setText("2110"); break;
                    case "July":tot.setText("2110"); break;
                    case "August":tot.setText("2110"); break;
                    case "September":tot.setText("2110"); break;
                    case "October":tot.setText("2110"); break;
                    case "November":tot.setText("2110"); break;
                    case "December":tot.setText("2110"); break;
                    case "January":tot.setText("2110"); break;
                    case "February":tot.setText("2110"); break;
                    case "March":tot.setText("2110"); break;
                    default : JOptionPane.showMessageDialog(null,"Select Month");
                }
            }
            else
            if(c1.equals("9")||c1.equals("10"))
            {
                switch(c2)
                {
                    case "April":tot.setText("9060"); break;
                    case "May":tot.setText("2360"); break;
                    case "June":tot.setText("2360"); break;
                    case "July":tot.setText("2360"); break;
                    case "August":tot.setText("2360"); break;
                    case "September":tot.setText("2360"); break;
                    case "October":tot.setText("2360"); break;
                    case "November":tot.setText("2360"); break;
                    case "December":tot.setText("2360"); break;
                    case "January":tot.setText("2360"); break;
                    case "February":tot.setText("2360"); break;
                    case "March":tot.setText("2360"); break;
                    default : JOptionPane.showMessageDialog(null,"Select Month");
                }
            }
            else
            if(c1.equals("11_COMMERCE")||c1.equals("11_Science"))
            {
                switch(c2)
                {
                    case "April":tot.setText("9150"); break;
                    case "May":tot.setText("2450"); break;
                    case "June":tot.setText("2450"); break;
                    case "July":tot.setText("2450"); break;
                    case "August":tot.setText("2450"); break;
                    case "September":tot.setText("2450"); break;
                    case "October":tot.setText("2450"); break;
                    case "November":tot.setText("2450"); break;
                    case "December":tot.setText("2450"); break;
                    case "January":tot.setText("2450"); break;
                    case "February":tot.setText("2450"); break;
                    case "March":tot.setText("2450"); break;
                    default : JOptionPane.showMessageDialog(null,"Select Month");
                }
            }
            else
            if(c1.equals("12_COMMERCE")||c1.equals("12_Science"))
            {
                switch(c2)
                {
                    case "April":tot.setText("9440"); break;
                    case "May":tot.setText("2740"); break;
                    case "June":tot.setText("2740"); break;
                    case "July":tot.setText("2740"); break;
                    case "August":tot.setText("2740"); break;
                    case "September":tot.setText("2740"); break;
                    case "October":tot.setText("2740"); break;
                    case "November":tot.setText("2740"); break;
                    case "December":tot.setText("2740"); break;
                    case "January":tot.setText("2740"); break;
                    case "February":tot.setText("2740"); break;
                    case "March":tot.setText("2740"); break;
                    default : JOptionPane.showMessageDialog(null,"Select Month");
                }
            }
            else
            JOptionPane.showMessageDialog(null,"Select Class.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubmitFEES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubmitFEES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubmitFEES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubmitFEES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubmitFEES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JTextField adno;
    private javax.swing.JTextField april;
    private javax.swing.JTextField aug;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JTextField clas;
    private javax.swing.JComboBox<String> co2;
    private javax.swing.JTextField dec;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField feb;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jan;
    private javax.swing.JTextField july;
    private javax.swing.JTextField june;
    private javax.swing.JList l2;
    private javax.swing.JTextField march;
    private javax.swing.JTextField may;
    private javax.swing.JTextField mob;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nov;
    private javax.swing.JTextField oct;
    private javax.swing.JTextField sec;
    private javax.swing.JTextField sept;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField tot;
    // End of variables declaration//GEN-END:variables
}
